/* this code was generated by E', the restricted Digamma compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <gc.h>
#include <math.h>
#include <sys/param.h>
#include <fcntl.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <dirent.h>
#include <signal.h>
#include <errno.h>
#include <stdarg.h>
#include "vesta.h"
#define nil NULL
#define STRUE tl_env->strue
#define SFALSE tl_env->sfalse
#define SSUCC tl_env->ssucc
#define SUNSUCC tl_env->sunsucc
#define SNIL tl_env->snil
static Symbol *tl_env = nil;
SExp *
fib(SExp *i,SExp *j,SExp *n)
{
	SExp *ret = nil, *i2 = nil,*j3 = nil,*n4 = nil;
	int s1 = 1;
	while(s1)
	{
		
SExp *it5 = flte(list(2,n,makeinteger(0)));

        if(it5 == nil || it5->type == NIL || ((it5->type == BOOL || it5->type == GOAL) && it5->object.c))
        {
                s1 = 0;
                ret = i;
        }
        else
        {
                i2 = fplus(list(2,i,j));
j3 = i;
n4 = fsubt(list(2,n,makeinteger(1)));
i = i2;
j = j3;
n = n4;

        }

	}
	return ret;
}
SExp *
scheme_main()
{
    SExp *ret = nil;
    f_princ(list(1,fib(makeinteger(0),makeinteger(1),makeinteger(10))),tl_env);
    newline(SNIL,tl_env);
    f_princ(list(1,fib(makeinteger(0),makeinteger(1),makeinteger(20))),tl_env);
    newline(SNIL,tl_env);
    f_princ(list(1,fib(makeinteger(0),makeinteger(1),makeinteger(30))),tl_env);
    newline(SNIL,tl_env);
    f_princ(list(1,fib(makeinteger(0),makeinteger(1),makeinteger(32))),tl_env);
    ret = newline(SNIL,tl_env);
    return ret;
}
void
init_j1()
{
	tl_env = init_env();

}
int
main()
{
    gc_init();
    init_j1();
    scheme_main();
}
