(def fib (fn (j i n)
	  (if (<= n 0)
	   i
	   (fib i (+ i j) (- n 1)))))
(display (fib 1 0 2))
(newline)
(display (fib 1 0 4))
(newline)
(display (fib 1 0 6))
(newline)
(display (fib 1 0 8))
(newline)
(display (fib 1 0 22))
	(newline)
	(quit)
