(define-macro let (bind :body letbody)
	(display "Bind: ")
	(display bind)
	(newline)
	(with unbounds (unzip bind)
		(display "Unbounds: ")
		(display unbounds)
		(newline)
		(cons (cons 'fn (cons (car unbounds) letbody)) (car (cdr unbounds)))))