(load 'hydra.ss)
(define code '(car (cdr (cons 1 (cons 2 '())))))
(define hlap (hydra@eval code *tlenv*))
(display "original source code: ")
(write code)
(newline) 
(display "HLAP output: ")
(display hlap)
(newline)
(display (vm@eval hlap *tlenv*))
(newline)
